In [1]:
import numpy as np

In [22]:
arr1 = np.array([[0,1,2,3,4,5,6,7,8,9,10]])
arr2 = np.array([range(0,11)])

In [17]:
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9 10]]


In [18]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
arrT = arr1.T

In [20]:
arrT

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [23]:
arr2.T

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [24]:
arr2.shape

(1, 11)