In [1]:
import numpy as np
from scipy import misc
import matplotlib.pyplot as plt

In [2]:
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
from skimage import data
import imageio

In [ ]:
photo_data = imageio.imread('sd-3layers.jpg')
print(type(photo_data))

In [ ]:
plt.figure()
plt.imshow(photo_data)

In [ ]:
# dimensions of the image
print(photo_data.shape)
#print(photo_data)


In [ ]:
photo_data.size, photo_data.min(), photo_data.max()

In [ ]:
# get the details of an individual pixel

print(photo_data[150,250])
print('R', photo_data[150,250, 0])
print('G', photo_data[150,250, 1])
print('B', photo_data[150,250, 2])

In [ ]:
# change an individual pixel

photo_data[150, 250] = 50
plt.figure()
plt.imshow(photo_data)

In [ ]:
# change a range of pixels

photo_data = imageio.imread('sd-3layers.jpg')
photo_data[200:800, : , :] = 250
plt.figure()
plt.imshow(photo_data)

In [ ]:
photo_data = imageio.imread('sd-3layers.jpg')
photo_data = photo_data + 250
plt.figure()
plt.imshow(photo_data)

In [ ]:
photo_data = imageio.imread('sd-3layers.jpg')
plt.figure()
plt.imshow(photo_data)

low_value_filter = photo_data < 150


print(photo_data.shape)
print(photo_data[low_value_filter].shape)

# to plot with the filter

photo_data[low_value_filter] = 0
plt.figure()
plt.imshow(photo_data)



In [ ]:
photo_data = imageio.imread('sd-3layers.jpg')
rows_range = np.arange(len(photo_data))
cols_range = np.arange(len(photo_data))
print(rows_range.shape, type(rows_range))

In [ ]:
photo_data[rows_range, cols_range, :] = 255
plt.figure()
plt.imshow(photo_data)

<h1>Cutting out parts of an image, euclidian distance</h1>

In [22]:
photo_data = imageio.imread('sd-3layers.jpg')
total_rows, total_cols, total_layers = photo_data.shape

# mesh grids
x, y = np.ogrid[:total_rows, :total_cols]
print(photo_data.shape)
print(x.shape)
print(x)
print(y.shape)
print(y)
print(total_layers)

(3725, 4797, 3)
(3725, 1)
[[   0]
 [   1]
 [   2]
 ...
 [3722]
 [3723]
 [3724]]
(1, 4797)
[[   0    1    2 ... 4794 4795 4796]]
3


In [13]:
center_row, center_col = total_rows / 2, total_cols / 2
print(center_row)
print(center_col)

1862.5
2398.5


In [20]:
print((x - center_row).shape)
print((y - center_col).shape)

dist_from_center = (x - center_row)**2 + (y - center_col)**2
print(dist_from_center)
print()
radius = (total_rows / 2)**2
print(radius)
print()
circular_mask = (dist_from_center > radius)
print(circular_mask)

(3725, 1)
(1, 4797)
[[9221708.5 9216912.5 9212118.5 ... 9207326.5 9212118.5 9216912.5]
 [9217984.5 9213188.5 9208394.5 ... 9203602.5 9208394.5 9213188.5]
 [9214262.5 9209466.5 9204672.5 ... 9199880.5 9204672.5 9209466.5]
 ...
 [9210542.5 9205746.5 9200952.5 ... 9196160.5 9200952.5 9205746.5]
 [9214262.5 9209466.5 9204672.5 ... 9199880.5 9204672.5 9209466.5]
 [9217984.5 9213188.5 9208394.5 ... 9203602.5 9208394.5 9213188.5]]

3468906.25

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [21]:
photo_data[circular_mask] = 0
plt.figure()
plt.imshow(photo_data)

<h1>Masking a the bottom half of the image</h1>

In [24]:
x, y  = np.ogrid[:total_rows, :total_cols]
half_upper = x < center_row
half_upper_mask = np.logical_and(half_upper, circular_mask)

In [25]:
photo_data = imageio.imread('sd-3layers.jpg')
photo_data[half_upper_mask] = 255
plt.figure()
plt.imshow(photo_data)

<h3>Showing items that have one strong color</h3>

In [34]:
photo_data = imageio.imread('sd-3layers.jpg')
red_mask = photo_data[:,:,0] < 150

# anything that has red < 150 will become 0
photo_data[red_mask] = 0
plt.figure()
plt.imshow(photo_data)

In [28]:
photo_data[:,:,0]

Array([[ 0,  0, 19, ..., 19,  0,  0],
       [30, 29, 25, ...,  1,  0,  0],
       [23, 16, 15, ...,  0,  0,  0],
       ...,
       [ 2,  2,  2, ...,  2,  2,  2],
       [ 2,  2,  2, ...,  2,  2,  2],
       [ 2,  2,  2, ...,  2,  2,  2]], dtype=uint8)

<h3>Mask on all three layers</h3>

In [38]:
photo_data = imageio.imread('sd-3layers.jpg')

red_mask = photo_data[:,:,0] > 150
green_mask = photo_data[:,:,1] > 100
blue_mask = photo_data[:,:,2] > 100

final_mask = np.logical_and(red_mask, green_mask, blue_mask)
photo_data[final_mask] = 255
plt.figure()
plt.imshow(photo_data)
